Project 2: The Next Web Clone
tmampa/Responsive-Web-Design-TNW pull request #1
Opened 2021-04-05 16:18 UTC by tmampa

In this project 

> We made the nav bar with flexbox
> Footer with flexbox
> Used media queries for responsiveness
> Added breakpoints for 2 other types of display

2021-04-05 17:44 UTC, henatan99 requested changes
# Changes Required :recycle:
Hi there, you did an excellent work :+1: :clap: :dancers: 
Yet you have a few changes before your project gets approved. See the below-summarized comments and inline comments in the PR. 
### Reminder: - This is your first review and you will be left with a maximum of two more reviews (re-reviews). If your project doesn't get approved at the third review, you will be asked to repeat the project from the beginning. 

## To Highlight 
- Your project fulfills most of the requirements at first CRR 
- Your project captures the original design very well

## To Improve [OPTIONAL]
- Improve semantic tag use in article elements (you have to use div element where you should have used article elements). Please see the inline comments 
- Refer the other inline comments for mandatory improvement of your project 

### Please, work on the requested changes and make another core review request.

### Reminder: - This is your first review and you will be left with a maximum of two more reviews (re-reviews). If your project doesn't get approved at the third review, you will be asked to repeat the project from the beginning.

2021-04-05 17:44 UTC, henatan99 commented on index.html
> +              <a class="logo-img" >
You forgot href value inside this a - tag.

2021-04-05 17:44 UTC, henatan99 commented on index.html
> +    <div class="showcase image-1 flex ">
This div element better b article for the sake of semantics. Use the same comment for the other articles in the showcase section

2021-04-05 17:44 UTC, henatan99 commented on index.html
> +        <h2>Latest funding rounds on Index.co  	&gt;</h2>
This title heading element should also have a link (a-tag)

2021-04-05 17:44 UTC, henatan99 commented on index.html
> +        </ul>
Wrap this ul element in a nav

2021-04-06 06:28 UTC, MkrtichSargsyan approved these changes
## _Status:_ Approved  :hamster: :rocket:
Hi Guys.

Congratulations on your hard work, your project is now approved, 
You can go ahead and merge this branch to the base branch of this repo.

Good luck in your future projects and happy coding :relaxed:

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

2021-04-06 06:37 UTC, merged